development:
  adapter: postgresql
  encoding: utf8
  database: nedviga_dev
  username: user
  password: 
  host: localhost
test:
  adapter: postgresql
  encoding: utf8
  database: nedviga_test
  username: user
  password: 
  host: localhost
